name: Multiplatform Build & Upload Artifacts
on:
  pull_request:
    branches:
      [ master ]
  workflow_dispatch:
  
jobs:
  build_artifacts_android:
    name: android_build
    runs-on: ubuntu-latest
    steps:
#
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        channel: 'stable'
        distribution: 'zulu'
        java-version: '16'
    - run: java -version
#
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: 'stable'
    - uses: subosito/flutter-action@v2
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: android_build
        path: build/app/outputs/apk/release/app-release.apk
        
      
